cargo-features = ["edition"]

[package]
edition = "2018"
authors = ["David Lewis <davidlewis@icloud.com>"]

name = "dingus"
version = "0.4.2"
description = "Easily apply environment variables loaded from a config file to a shell session."

homepage = "https://github.com/davidarmstronglewis/dingus"
readme = "README.md"

license = "MIT"

[dependencies]
clap = "^2.30.0"
serde = "^1.0.27"
serde_derive = "^1.0.27"
serde_yaml = "^0.7.3"
